name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    env:
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_AUTH_USERNAME: ${{ secrets.REDDIT_AUTH_USERNAME }}
      REDDIT_AUTH_PASSWORD: ${{ secrets.REDDIT_AUTH_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client and rsync
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client rsync
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/ssh-key.pem
          chmod 400 ~/.ssh/ssh-key.pem
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          
      - name: Test connection to EC2
        run: |
          ssh -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.AWS_EC2_CONN_ID }} "echo 'Connection successful!'"
      - name: Install Docker Requirements
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo docker run hello-world
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - name: Deploy Docker Compose to EC2
        run: |
          ssh -T -i ~/.ssh/ssh-key.pem ubuntu@${{ secrets.AWS_EC2_CONN_ID }} '
            set -x;  # Enable debugging
            if [ -d reddit-newsletter ]; 
            then 
              cd reddit-newsletter &&
              git status &&
              git pull --rebase &&
              git status;
            else
              git clone https://github.com/aniqp/reddit-newsletter.git &&
              cd reddit-newsletter;
            fi
            docker-compose down
            docker-compose up -d --build;
          '
        
